name: chinese_cities_view
description: 中国城市选择插件
version: 0.0.1
author: zhcode
homepage: https://www.zhcode.fun

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  assets:
    - assets/cities.json
